### ISSUE TITLE
Photo Page Loads Slowly

### ISSUE THREAD

**Issue by infantinoalex** [Doug-and-Victoria-Websites/wedding-website#3]
Hello, I was browsing this website and attempted to browse the `Photos` page.
It loads the photos at the same time as the page which is ruining the user experience since I cant see the navigation bar and the photos initially take a while to render properly.

When cached, I do not hit this issue (I hate caching so always `ctrl + F5` to clear the cache and refresh the page).

Please dynamically load the photos after the initial page load to improve the user experience or else I won't be able to use your website.

**Comment by Kevoot** [comment]
@infantinoalex Pages with heavy media content are expected to load with differing speeds depending on the device and connection speed. I vote to close this issue as its working as expected and Alex just needs to get a better computer/connection.

**Comment by infantinoalex** [comment]
JS is the most powerful, easy to understand, and effecient language in the world and yet I barely see any JS in this website.
Should really take advantage of the SIMPLE JS stuff in the photos page to dynamically load.

**Comment by Kevoot** [comment]
Speaking on behalf of the author, WeddingV2 will include dynamic page loading and addition of Typescript definitions, possible use of React in the UI. WeddingV3 will undoubtedly include tools for doxxing @infantinoalex "effecient"ly

**Comment by doug-and-victoria** [comment]
Be grateful I didn't mark it as SPAM... :P
